export const SET_CONNECTION = 'SET_CONNECTION'
export const GET_CONNECTION = 'GET_CONNECTION'
export const CREATE_ELECTION ='CREATE_ELECTION'
export const AUTHENTICATION_STATUS="AUTHENTICATION_STATUS"
export const SIGN_IN="SIGN_IN"
export const SIGN_OUT="SIGN_OUT"
export const ADD_VOTER="ADD_VOTER"
